---
title: Blog Post 3
author: Maryam Bhuttor, Priya Kaneria, Veer Sawhney, Tessa Sharma
date: '2022-10-28'
slug: []
categories: []
tags: []
description: Blog-Post3.
toc: yes
authors: []
series: []
lastmod: '2022-10-28'
featuredVideo: ~
featuredImage: ~
---

We are examining the CO2 Emissions dataset in Blogpost 3.

Our data highlights the physical effects of climate change in the US in comparison to a number of financial indicators over time. Data collectors analyzed factors related to CO2 emissions related to human activities such as deforestation and use of electricity. 

The equitable data practice of justice is relevant to this dataset and its analysis because climate change negatively impacts minority populations. By examining the correlation between climate change and economic outputs such as GDP growth, we can begin to consider how climate change unfairly impacts certain communities. We can also examine the correlation between climate change and human activities such as deforestation and electricity use to examine conservation efforts over time. The point of this study might be to emphasize the importance of furthering conservation efforts to reduce CO2 emissions.

The practice of beneficence is also relevant to this dataset and its analysis because reducing CO2 emission ultimately will benefit this and future generations. To adhere to the practice of beneficence, it is important that we recognize the benefits of tackling climate change while analyzing the data. The implications of the analyses will hopefully point to concrete solutions for mitigating the harmful effects of climate change.

The data has some limitations worth discussing; our analyses are limited here to the approximately two decades of CO2 emission data, so though some information in the dataset dates back to 1972, we cannot analyze its impact on CO2 emissions as closely. The data also examines these variables for the US as a whole; while we may be able to draw general conclusions about climate change for the US as a whole, we are missing the breakdown of how these factors present in different regions of the US. This may limit our ability to analyze more specifically how CO2 emissions have impacted certain regions and what areas have affected the changes we will examine.

It is also important to note that our data could potentially be misused and manipulated to further false narratives about climate change. Analyses of these data could be used to draw false conclusions about why CO2 emissions have or have not changed, or that changes are not significant. Correlations can be used to draw false conclusions about the data and what is causing these factors to change or stay the same.
