---
title: "corn dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
install.packages("flexdashboard")


---
title: "dashboard"
output: flexdashboard::flex_dashboard:
    vertical_layout: fill
date: "2022-12-17"
---



```{r}
library(tidyverse)
library(plotly)
#install.packages("DT")
library(DT)
```


### Chart 1 Plotly Corn
```{r}
library(tidyverse)
suppressMessages(library(plotly))

library(tidyr)

# barley_data_3 <- read_csv(here::here("dataset", "barley/crop_p015_t005.csv"),skip = 5)
# barley_data_3<- barley_data_3[-2,3:ncol(barley_data_3)] %>% drop_na(Year) %>% head(-1)
#
# barley_data_4 <- read_csv(here::here("dataset", "barley/crop_p016_t010.csv"),skip = 5)
# barley_data_4<- barley_data_4[-2,3:ncol(barley_data_4)] %>% drop_na(Year) %>% head(-1)
#
# barley_data <- barley_data_3%>%bind_rows(barley_data_4)
# barley_data <- barley_data %>% type_convert()
#
# barley_co2_data <- co2_data_clean %>% left_join(barley_data, by = c("Time" = "Year"))

#write_csv(co2_data_clean, file = here::here("dataset", "clean_co2.csv"))

#save(co2_data_clean, file = here::here("dataset/clean_co2.RData"))

#barley_co2_data <- co2_data_clean %>% left_join(barley_data, by = c("Time" = "Year"))




corn <- corn_co2_data
#corn <- read_csv(here::here("dataset", "corn_co2_data"))


g <- ggplot(corn_co2_data, aes(x = Time, y = Production, color = CO2_emissions_kt.x,
  text = paste("Year:", Time, "<br>", "Production Output:", Production, "<br>", "GDP Growth Percent:", GDP_growth))) +
  geom_point(position = "jitter")
ggplotly(g, tooltip = "text")
```


### Chart 2 Animation Corn
```{r}
#install.packages("gapminder")
corn <- corn_co2_data
data(corn)
gg <- ggplot(corn,
  aes(x = Time, y = Production,
    color = CO2_emissions_kt.x,
    size = corn$`Yield per acre`)) +
  geom_point(alpha = 0.1) +
  geom_point(aes(frame = Time)) +
  scale_x_log10()
ggplotly(gg)



#data(gapminder, package = "gapminder")
#gg <- ggplot(gapminder,
#  aes(x = gdpPercap, y = lifeExp,
#    color = continent,
 #   size = pop)) +
  #geom_point(alpha = 0.1) +
#  geom_point(aes(frame = year)) +
 # scale_x_log10()
#ggplotly(gg)
```


### formatted table corn
```{r}
#install.packages("formattable")


library(DT)
corn %>%
  datatable(rownames = FALSE, options = list(pageLength = 5))

corn %>% select(Time, CO2_emissions_kt.x, Production) %>%
  #filter(row_number() %% 20 == 0) %>%
  formattable(list(displ = color_tile("white", "orange"),
    area(col = c(CO2_emissions_kt.x)) ~ normalize_bar("green", 0.2),
    Production = formatter("span",
      style = Production ~ ifelse(Production<=200000, style(color = "red"),
        ifelse(Production>20000, style(color = "blue"),
          style(color = "black"))))))



# mpg %>% select(hwy, manufacturer, model, cyl, displ) %>%
#   filter(row_number() %% 20 == 0) %>%
#   formattable(list(displ = color_tile("white", "orange"),
#     area(col = c(hwy)) ~ normalize_bar("green", 0.2),
#     cyl = formatter("span",
#       style = cyl ~ ifelse(cyl==4, style(color = "red"),
#         ifelse(cyl==6, style(color = "blue"),
#           style(color = "black"))))))



# library(DT)
# mpg %>%
#   datatable(rownames = FALSE, options = list(pageLength = 5))


```





```{r}
# install.packages("d3scatter")
# library(d3scatter)
# shared_mtcars <- SharedData$new(mtcars)
# bscols(widths = c(3,NA,NA),
#   list(
#     filter_checkbox("cyl", "Cylinders", shared_mtcars, ~cyl, inline = TRUE),
#     filter_slider("hp", "Horsepower", shared_mtcars, ~hp, width = "100%"),
#     filter_select("auto", "Automatic", shared_mtcars, ~ifelse(am == 0, "Yes", "No"))
#   ),
#   d3scatter(shared_mtcars, ~wt, ~mpg, ~factor(cyl), width="100%", height=250),
#   d3scatter(shared_mtcars, ~hp, ~qsec, ~factor(cyl), width="100%", height=250)
# )
```

