---
title: Corn Analysis
description:
toc: true
featuredVideo:
featuredImage:
draft: false
---

This comes from the file `content/corn_analysis.Rmd`.

```{r packages, echo=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
#install.packages("forecast")
require(forecast)
library(readr)
library(tidyr)
```

```{r cleaning_data, echo=FALSE}
## CLEAN THE DATA
co2_data_clean <- read.csv(here::here("dataset/clean_co2.csv"))

#write_csv(co2_data_clean, file = here::here("dataset", "clean_co2.csv"))

#save(co2_data_clean, file = here::here("dataset/clean_co2.RData"))
co2_data_clean <- co2_data_clean[,-1]

co2_data_clean[co2_data_clean == ".."] = NA
co2_data_clean <- co2_data_clean %>% type_convert()
co2_data_clean[is.na(co2_data_clean)] = 0


co2_data_clean <- co2_data_clean[19:50,]

for(i in 2:ncol(co2_data_clean)){
  co2_data_clean[,i][(co2_data_clean[,i]==0)] = mean(co2_data_clean[,i])
}

```

```{r corn_co2_dataset}
# used barley datasets for col names
barley_data_3 <- read_csv(here::here("dataset", "barley/crop_p015_t005.csv"),skip = 5)
barley_data_3<- barley_data_3[-2,3:ncol(barley_data_3)] %>% drop_na(Year) %>% head(-1)

barley_data_4 <- read_csv(here::here("dataset", "barley/crop_p016_t010.csv"),skip = 5)
barley_data_4<- barley_data_4[-2,3:ncol(barley_data_4)] %>% drop_na(Year) %>% head(-1)



corn_data_3 <-read_csv(here::here("dataset", "corn/crop_p031_t024.csv"),skip = 7)
corn_data_3<- corn_data_3[-2,3:ncol(corn_data_3)] %>% drop_na(Year) %>%filter(nchar(Year)==4)
colnames(corn_data_3) <- colnames(barley_data_3) ## (barley_data_3)
corn_data_3 <- corn_data_3[,1:7]
# View(corn_data_3)

corn_data_4 <- read_csv(here::here("dataset", "corn/crop_p032_t034.csv"),skip = 7)
corn_data_4<- corn_data_4[-2,3:ncol(corn_data_4)] %>% drop_na(Year) %>%filter(nchar(Year)==4)
colnames(corn_data_4) <- colnames(barley_data_4) ## (barley_data_4)
corn_data_4 <- corn_data_4[,1:7]
# View(corn_data_4)


corn_data <- corn_data_3%>%bind_rows(corn_data_4) 
corn_data <- corn_data %>% type_convert()
View(corn_data)

corn_co2_data <- co2_data_clean %>% left_join(corn_data, by = c("Time" = "Year"))
View(corn_co2_data)

```


```{r corn_timeseries, echo=FALSE}

Year <- corn_co2_data %>% pull(Time)
Production <- corn_co2_data %>% pull(Production)
co_emit <- corn_co2_data %>% pull(CO2_emissions_kt)

corn_ts <- ggplot(corn_co2_data, aes(x=Year, y=Production)) +
  geom_line() +
  xlab("")
corn_ts

```
In our time series analysis above, we analyze the production of corn over time.

```{r corn_stats}
ggAcf(corn_co2_data$`Area harvested`)  ###use difference 

ggAcf(diff(corn_co2_data$`Area harvested`)) ## no autocorrelation


# co2 emission
ggAcf(corn_co2_data$CO2_emissions_kt) ##persistent  autocorrelation 
ggAcf(diff(corn_co2_data$CO2_emissions_kt)) #increase of c02 over time, a good plot


#corn_co2_data %>% ggplot(aes(x = diff(`Area harvested`), y = diff(CO2_emissions_kt))) + geom_point()

diff_df <- data.frame(diff_area = diff(corn_co2_data$`Area harvested`), diff_co2 = diff(corn_co2_data$CO2_emissions_kt) )
diff_df %>% ggplot(aes(x = diff_area, y = diff_co2)) + geom_point()+ geom_smooth()
### weak correlation between co2 and harvested

corn_co2_data %>% ggplot(aes(x = `Area harvested`, y = CO2_emissions_kt)) + geom_point()+ geom_smooth()
##there is weak correlation here, the relation seems to be cubic

lm1 <- (lm(`Area harvested`~ poly(CO2_emissions_kt,3), corn_co2_data)) 
summary(lm1)

lm1_diff <-lm(diff_area ~ diff_co2, diff_df) 
summary(lm1_diff)

# No significant association

ggAcf(lm1$residuals)
ggAcf(lm1_diff$residuals)


```





