---
title: Flaxseed Analysis
description:
toc: true
authors: []
tags: []
categories: []
series: []
date: 2022-12-18T23:36:41-05:00
lastmod: 2022-12-18T23:36:41-05:00
featuredVideo:
featuredImage:
draft: false
---


This comes from the file `content/flaxseed_analysis.Rmd`.

```{r packages, echo=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
#install.packages("forecast")
require(forecast)
library(readr)
library(tidyr)
```

```{r cleaning_data, echo=FALSE}
## CLEAN THE DATA
co2_data_clean <- read.csv(here::here("dataset/clean_co2.csv"))

#write_csv(co2_data_clean, file = here::here("dataset", "clean_co2.csv"))

#save(co2_data_clean, file = here::here("dataset/clean_co2.RData"))
co2_data_clean <- co2_data_clean[,-1]

co2_data_clean[co2_data_clean == ".."] = NA
co2_data_clean <- co2_data_clean %>% type_convert()
co2_data_clean[is.na(co2_data_clean)] = 0


co2_data_clean <- co2_data_clean[19:50,]

for(i in 2:ncol(co2_data_clean)){
  co2_data_clean[,i][(co2_data_clean[,i]==0)] = mean(co2_data_clean[,i])
}

```

```{r corn_co2_dataset}
# used barley datasets for col names
barley_data_3 <- read_csv(here::here("dataset", "barley/crop_p015_t005.csv"),skip = 5)
barley_data_3<- barley_data_3[-2,3:ncol(barley_data_3)] %>% drop_na(Year) %>% head(-1)

barley_data_4 <- read_csv(here::here("dataset", "barley/crop_p016_t010.csv"),skip = 5)
barley_data_4<- barley_data_4[-2,3:ncol(barley_data_4)] %>% drop_na(Year) %>% head(-1)



flaxseed_data_3 <- read_csv(here::here("dataset", "flaxseed/crop_p086_t049.csv"), 
                            col_types = cols(`49` = col_skip(), t = col_skip(), 
                                             `Crop Production Historical Track Records: Released April 11, 2022, by the National Agricultural Statistics Service (NASS), Agricultural Statistics Board, United States Department of Agriculture (USDA).` = col_double(), 
                                             ...3 = col_double(), u = col_skip()), 
                            skip = 7)
colnames(flaxseed_data_3) <- colnames(barley_data_3)

flaxseed_data_3 <- flaxseed_data_3 %>% drop_na(Year)

# View(flaxseed_data_3)
flaxseed_data_4 <- read_csv(here::here("dataset", "flaxseed/crop_p087_t050.csv"), 
                            col_types = cols(`50` = col_skip(), t = col_skip(), 
                                             `Crop Production Historical Track Records: Released April 11, 2022, by the National Agricultural Statistics Service (NASS), Agricultural Statistics Board, United States Department of Agriculture (USDA).` = col_double(), 
                                             ...3 = col_double(), u = col_skip()), 
                            skip = 7)
colnames(flaxseed_data_4) <- colnames(barley_data_4)

flaxseed_data_4 <- flaxseed_data_4 %>% drop_na(Year)

# View(flaxseed_data_4)
flaxseed_data_3 <- flaxseed_data_3 %>% type_convert()
flaxseed_data <- flaxseed_data_3%>%bind_rows(flaxseed_data_4) 
View(flaxseed_data)

flaxseed_co2_data <- co2_data_clean %>% left_join(flaxseed_data, by = c("Time" = "Year"))


flaxseed_co2_data <- flaxseed_co2_data %>% filter(CO2_emissions_kt != "..") %>% type_convert()

View(flaxseed_co2_data)

```


```{r flaxseed_timeseries}

Year <- flaxseed_co2_data %>% pull(Time)
Production <- flaxseed_co2_data %>% pull(Production)
co_emit <- flaxseed_co2_data %>% pull(CO2_emissions_kt)

flaxseed_ts <- ggplot(flaxseed_co2_data, aes(x=Year, y=Production)) +
  geom_line() +
  xlab("")
flaxseed_ts


```

In our time series analysis above, we analyze the production of flaxseed over time.


```{r flaxseed_stats}

ggAcf(flaxseed_co2_data$`Area harvested`)  ###use difference 
ggAcf(diff(flaxseed_co2_data$`Area harvested`)) ## no autocorrelation


# co2 emission
ggAcf(flaxseed_co2_data$CO2_emissions_kt) ##persistent  autocorrelation 
ggAcf(diff(flaxseed_co2_data$CO2_emissions_kt)) #increase of c02 over time, a good plot


#flaxseed_co2_data %>% ggplot(aes(x = diff('Area harvested'), y = diff(CO2_emissions_kt))) + geom_point()

diff_df <- data.frame(diff_area = diff(flaxseed_co2_data$`Area harvested`), diff_co2 = diff(flaxseed_co2_data$CO2_emissions_kt) )
diff_df %>% ggplot(aes(x = diff_area, y = diff_co2)) + geom_point()+ geom_smooth()
### weak correlation between co2 and harvested

flaxseed_co2_data %>% ggplot(aes(x = `Area harvested`, y = CO2_emissions_kt)) + geom_point()+ geom_smooth()
##there is very strong correlation here

lm2 <- (lm(`Area harvested`~ CO2_emissions_kt, flaxseed_co2_data)) 
summary(lm2)
#High correlation

lm2_diff <-lm(diff_area ~ diff_co2, diff_df) 
summary(lm2_diff)
#differenced data has no correlation, differencing is not required

ggAcf(lm2$residuals)
ggAcf(lm1_diff$residuals)


```




