---
title: Oat Analysis
description:
toc: true
featuredVideo:
featuredImage:
draft: false
---

This comes from the file `content/oat_analysis.Rmd`.

```{r packages, echo=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
#install.packages("forecast")
require(forecast)
library(readr)
library(tidyr)
```

```{r cleaning_data}
## CLEAN THE DATA
co2_data_clean <- read.csv(here::here("dataset/clean_co2.csv"))

#write_csv(co2_data_clean, file = here::here("dataset", "clean_co2.csv"))

#save(co2_data_clean, file = here::here("dataset/clean_co2.RData"))
co2_data_clean <- co2_data_clean[,-1]

co2_data_clean[co2_data_clean == ".."] = NA
co2_data_clean <- co2_data_clean %>% type_convert()
co2_data_clean[is.na(co2_data_clean)] = 0


co2_data_clean <- co2_data_clean[19:50,]

for(i in 2:ncol(co2_data_clean)){
  co2_data_clean[,i][(co2_data_clean[,i]==0)] = mean(co2_data_clean[,i])
}

```


```{r oat_co2_dataset}
# used barley datasets for col names
barley_data_3 <- read_csv(here::here("dataset", "barley/crop_p015_t005.csv"),skip = 5)
barley_data_3<- barley_data_3[-2,3:ncol(barley_data_3)] %>% drop_na(Year) %>% head(-1)

barley_data_4 <- read_csv(here::here("dataset", "barley/crop_p016_t010.csv"),skip = 5)
barley_data_4<- barley_data_4[-2,3:ncol(barley_data_4)] %>% drop_na(Year) %>% head(-1)


oat_dataset_3<- read_csv(here::here("dataset", "oat/crop_p124_t077.csv"),skip = 5)
oat_dataset_3<- oat_dataset_3 %>% drop_na(Year) %>%filter(nchar(Year)==4) %>% drop_na(Year) %>% type_convert()
oat_dataset_3<- oat_dataset_3[-2,3:ncol(oat_dataset_3)] %>% drop_na(Year) %>% head(-1)
colnames(oat_dataset_3) <- colnames(barley_data_3)
# View(oat_dataset_3)


oat_dataset_4<- read_csv(here::here("dataset", "oat/crop_p125_t078.csv"),skip = 5)
oat_dataset_4<- oat_dataset_4 %>% drop_na(Year) %>%filter(nchar(Year)==4) %>% drop_na(Year) %>% type_convert()
oat_dataset_4<- oat_dataset_4[-2,3:ncol(oat_dataset_4)] %>% drop_na(Year) %>% head(-1)
colnames(oat_dataset_4) <- colnames(barley_data_4)
# View(oat_dataset_4)


oat_data <- oat_dataset_3%>%bind_rows(oat_dataset_4) 
View(oat_data)

oat_co2_data <- co2_data_clean %>% left_join(oat_data, by = c("Time" = "Year"))
# View(oat_co2_data)

oat_co2_data <- oat_co2_data %>% filter(CO2_emissions_kt != "..") %>% type_convert()
View(oat_co2_data)

```


```{r oat_timeseries}

Year <- oat_co2_data %>% pull(Time)
Production <- oat_co2_data %>% pull(Production)
co_emit <- oat_co2_data %>% pull(CO2_emissions_kt)

oat_ts <- ggplot(oat_co2_data, aes(x=Year, y=Production)) +
  geom_line() +
  xlab("")
oat_ts

```
In our time series analysis above, we analyze the production of oats over time.

```{r oat_stats}
ggAcf(oat_co2_data$`Area harvested`)  ###use difference 
ggAcf(diff(oat_co2_data$`Area harvested`)) ## no autocorrelation


# co2 emission
ggAcf(oat_co2_data$CO2_emissions_kt) 
ggAcf(diff(oat_co2_data$CO2_emissions_kt)) 


oat_co2_data %>% ggplot(aes(x = diff('Area harvested'), y = diff(CO2_emissions_kt))) + geom_point()

diff_df <- data.frame(diff_area = diff(oat_co2_data$`Area harvested`), diff_co2 = diff(oat_co2_data$CO2_emissions_kt) )
diff_df %>% ggplot(aes(x = diff_area, y = diff_co2)) + geom_point()+ geom_smooth()

oat_co2_data %>% ggplot(aes(x = `Area harvested`, y = CO2_emissions_kt)) + geom_point()+ geom_smooth()


lm2 <- (lm(`Area harvested`~ CO2_emissions_kt, oat_co2_data)) 

lm2_diff <-lm(diff_area ~ diff_co2, diff_df) 

ggAcf(lm2$residuals)
ggAcf(lm2_diff$residuals)

oat_co2_data %>% ggplot(aes(y = `Area harvested`, x = (CO2_emissions_kt))) + geom_point()
oat_co2_data %>% ggplot(aes(y = `Production`, x = (CO2_emissions_kt))) + geom_point()
oat_co2_data %>% ggplot(aes(y = `Area planted`, x = (CO2_emissions_kt))) + geom_point()
oat_co2_data %>% ggplot(aes(y = `Yield per acre`, x = (CO2_emissions_kt))) + geom_point()

```




